
export const AUTH = {
	AUTH: 'AUTH',
  UPDATE: 'UPDATE'
}

export const JOURNEY = {
	GET_DEFAULT_CIRCLES: 'GET_DEFAULT_CIRCLES'
}


export const EVENTS = {
  SAVE_EVENTS: 'SAVE_EVENTS',
  SAVE_CALENDARS: 'SAVE_CALENDARS',
  SAVE_CALENDAR: 'SAVE_CALENDAR',
  SELECT_CALENDAR: 'SELECT_CALENDAR',
  CHANGE_CALENDAR_STATUS: 'CHANGE_CALENDAR_STATUS',
  DELETE_EVENT: 'DELETE_EVENT',
  INSERT_GOOGLE_EVENT: 'INSERT_GOOGLE_EVENT',
  UPDATE_GOOGLE_EVENT: 'UPDATE_GOOGLE_EVENT',
  GET_LOCAL_CALENDARS: 'GET_LOCAL_CALENDARS',
  SAVE_LOCAL_EVENT: 'SAVE_LOCAL_EVENT',
  GET_LOCAL_EVENTS: 'GET_LOCAL_EVENTS',
  DELETE_LOCAL_EVENT: 'DELETE_LOCAL_EVENT',
  UPDATE_LOCAL_EVENT: 'UPDATE_LOCAL_EVENT',
  GET_CIRLCES: 'GET_CIRLCES',
  SAVE_COLOR: 'SAVE_COLOR',
  CHANGE_LOCAL_CALENDAR_COLOR: 'CHANGE_LOCAL_CALENDAR_COLOR',
  GET_COLOR: 'GET_COLOR',
  GET_BROKER_LOCAL_EVENTS: 'GET_BROKER_LOCAL_EVENTS',
  GET_BROKER: 'GET_BROKER',
  GET_AGENT_LOCAL_EVENTS: 'GET_AGENT_LOCAL_EVENTS',
  SET_GOOGLE_CAL_STATUS: 'SET_GOOGLE_CAL_STATUS',
  GET_AGENT: "GET_AGENT",
  ERROR_EVENT_UPDATE: "ERROR_EVENT_UPDATE",
  REFRESH_ERROR: "REFRESH_ERROR",
  SHARE_CIRCLE: "SHARE_CIRCLE",
  REFRESH_MESSAGE: "REFRESH_MESSAGE",
  GET_BROKER_CALENDARS: "GET_BROKER_CALENDARS",
  DELETE_GOOGLE_CALENDAR: "DELETE_GOOGLE_CALENDAR",
  CHANGE_DISPLAY: "CHANGE_DISPLAY",
}

export const CIRCLES = {
	GET_ALL : 'GET_ALL_CIRCLES',
	CREATE : 'CREATE_CIRCLES',
	UPDATE : 'UPDATE_CIRCLES',
	DELETE : 'DELETE_CIRCLES',
  GET_CIRCLE_LEADS : 'GET_CIRCLE_LEADS'
}

export const LEADS = {
	GET_ALL : 'GET_ALL_LEADS',
	CREATE : 'CREATE_LEADS',
	UPDATE : 'UPDATE_LEADS',
	DELETE : 'DELETE_LEADS',
	GET_MY_ALL: 'GET_MY_ALL',
  BULK_LEAD_CREATE: 'BULK_LEAD_CREATE',
  PATCH_LEAD: 'PATCH_LEAD',
  GET_CURRENT_LEAD: 'GET_CURRENT_LEAD',
  LEAD_CIRCLES : 'LEAD_CIRCLES',
  RELATED_CONTACTS : 'RELATED_CONTACTS',
  DOC_FILES : 'DOC_FILES',
  TAGS_ALL : 'TAGS_ALL'
}

export const TASKS = {
	GET_ALL : 'GET_ALL_TASKS',
	CREATE : 'CREATE_TASKS',
	UPDATE : 'UPDATE_TASKS',
	DELETE : 'DELETE_TASKS'
}

export const PROPERTY = {
	GET_ALL: 'GET_PROPERTIES',
	SEARCH_ALL: 'SEARCH_ALL',
  SET_ACTIVE: 'SET_ACTIVE',
  SET_PAGE_STATE: 'SET_PAGE_STATE',
  SELECT_PROPERTY: 'SELECT_PROPERTY',
}

export const INBOX = {
  GET_MESSAGES: 'GET_MESSAGES',
  UPDATE_GMAIL_API_STATUS: 'UPDATE_GMAIL_API_STATUS',
  GET_INBOX_MESSAGES: 'GET_INBOX_MESSAGES',
  GET_SENT_MESSAGES: 'GET_SENT_MESSAGES',
  GET_TRASH_MESSAGES: 'GET_TRASH_MESSAGES',
  GET_DRAFT_MESSAGES: 'GET_DRAFT_MESSAGES',
  TRASH_MESSAGE_BY_IDS: 'TRASH_MESSAGE_BY_IDS',
  NEW_SENT_MESSAGE: 'NEW_SENT_MESSAGE',
  NEW_DRAFT_MESSAGE: 'NEW_DRAFT_MESSAGE',
  SET_UNREAD_COUNT: 'SET_UNREAD_COUNT'
}

export const COMMON = {
  	SERVER_REQUEST: 'SERVER_REQUEST',
  	SERVER_FAILURE: 'SERVER_FAILURE',
  	SERVER_SUCCESS: 'SERVER_SUCCESS',
}

export const INTERACTIONS = {
  GET_ALL : 'GET_ALL_INTERACTIONS',
  FILTER : 'FILTER_INTERACTIONS',
  CREATE : 'CREATE_INTERACTIONS',
  UPDATE : 'UPDATE_INTERACTIONS',
  DELETE : 'DELETE_INTERACTIONS'
}


export const TEMPLATES = {
  GET_ALL : 'GET_ALL_TEMPLATES',
  CREATE : 'CREATE_TEMPLATES',
  UPDATE : 'UPDATE_TEMPLATES',
  DELETE : 'DELETE_TEMPLATES',
  PATCH : 'PATCH_TEMPLATES'
}

export const USERS = {
  GET_MY_TEAM_MEMBERS: 'GET_MY_TEAM_MEMBERS',
  GET_ALL : 'GET_ALL_USERS',
  CREATE_USER : 'CREATE_USER',
  UPDATE_USER : 'UPDATE_USER',
  DELETE : 'DELETE_USER',
  GET_PARENT: 'GET_PARENT',
  DELETE_MEMBER: 'DELETE_MEMBER'
}

export const NOTIFICATIONS = {
  GET_ALL_NOTIFICATIONS : 'GET_ALL_NOTIFICATIONS',
  UPDATE_NOTIFICATION : 'UPDATE_NOTIFICATION',

}
export const ANALYTICS = {
  GET_DATA: 'GET_DATA'
}

export const GAPI = {
  INIT: 'GAPI_INIT'
}

export const SETTING = {
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  RESET_PASSWORD: 'RESET_PASSWORD',
  UPDATE_CONNECT: 'UPDATE_CONNECT',
  GET_EMAIL_TEMPLATE: 'GET_EMAIL_TEMPLATE',   
  UPDATE_EMAIL_TEMPLATE: 'UPDATE_EMAIL_TEMPLATE'
}

export const SEARCH = {
  GET: 'GET_SEARCH',
  SAVE: 'SAVE_SEARCH'
}
